// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "ewallet/modules/transaction/statemachine/types"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, dao
func (_m *Repository) Create(ctx context.Context, dao types.TransDAO) (int64, error) {
	ret := _m.Called(ctx, dao)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, types.TransDAO) int64); ok {
		r0 = rf(ctx, dao)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, types.TransDAO) error); ok {
		r1 = rf(ctx, dao)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
