version: '3.1'

services:

  transactiondb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "transaction"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    ports:
      - 3306:3306
    volumes:
      - ./transaction.sql:/docker-entrypoint-initdb.d/transaction.sql

  walletdb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "wallet"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    ports:
      - 3307:3306
    volumes:
      - ./wallet.sql:/docker-entrypoint-initdb.d/wallet.sql
