// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "ewallet/modules/transaction/statemachine/types"
)

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, transType, transId
func (_m *Publisher) Publish(ctx context.Context, transType types.Type, transId int64) error {
	ret := _m.Called(ctx, transType, transId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Type, int64) error); ok {
		r0 = rf(ctx, transType, transId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
