// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BankWithdraw is an autogenerated mock type for the BankWithdraw type
type BankWithdraw struct {
	mock.Mock
}

// CreateWithdrawTransaction provides a mock function with given fields: ctx, cardID, amount
func (_m *BankWithdraw) CreateWithdrawTransaction(ctx context.Context, cardID int64, amount string) (string, error) {
	ret := _m.Called(ctx, cardID, amount)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) string); ok {
		r0 = rf(ctx, cardID, amount)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, cardID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
