// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	"ewallet/modules/transaction/statemachine/types"

	mock "github.com/stretchr/testify/mock"
)

// StateController is an autogenerated mock type for the StateController type
type StateController struct {
	mock.Mock
}

// NextState provides a mock function with given fields: state, status
func (_m *StateController) NextState(state types.State, status types.Status) types.State {
	ret := _m.Called(state, status)

	var r0 types.State
	if rf, ok := ret.Get(0).(func(types.State, types.Status) types.State); ok {
		r0 = rf(state, status)
	} else {
		r0 = ret.Get(0).(types.State)
	}

	return r0
}
