// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	"ewallet/modules/transaction/statemachine/types"

	mock "github.com/stretchr/testify/mock"
)

// StateHandlerGetter is an autogenerated mock type for the StateHandlerGetter type
type StateHandlerGetter struct {
	mock.Mock
}

// GetHandler provides a mock function with given fields: state
func (_m *StateHandlerGetter) GetHandler(state types.State) (types.StateHandler, error) {
	ret := _m.Called(state)

	var r0 types.StateHandler
	if rf, ok := ret.Get(0).(func(types.State) types.StateHandler); ok {
		r0 = rf(state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.StateHandler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(types.State) error); ok {
		r1 = rf(state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
